"""Update datetime columns to use UTC timezone

Revision ID: 36f317914d8c
Revises: 7fb74d561e02
Create Date: 2026-01-21 06:21:32.418442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36f317914d8c'
down_revision: Union[str, None] = '7fb74d561e02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
